name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0"

      - name: Get swift version
        run: swift --version

      - name: Clean build
        run: swift package clean

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v
