name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14 # Use macos-13, macos-14, or macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0"

      - name: Get swift version
        run: swift --version

      - name: Clean build
        run: swift package clean

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v
